/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TwindleBuildinfoDisplay {
        /**
          * Used for testing to pass in a mock version of `window`.
         */
        "windowProvider": Window;
        /**
          * Function to call to write to clipboard. This does not need to be set and only exists for injecting in a mock for unit testing.
         */
        "writeToClipboard": (_: string) => Promise<void>;
    }
}
declare global {
    interface HTMLTwindleBuildinfoDisplayElement extends Components.TwindleBuildinfoDisplay, HTMLStencilElement {
    }
    var HTMLTwindleBuildinfoDisplayElement: {
        prototype: HTMLTwindleBuildinfoDisplayElement;
        new (): HTMLTwindleBuildinfoDisplayElement;
    };
    interface HTMLElementTagNameMap {
        "twindle-buildinfo-display": HTMLTwindleBuildinfoDisplayElement;
    }
}
declare namespace LocalJSX {
    interface TwindleBuildinfoDisplay {
        /**
          * Used for testing to pass in a mock version of `window`.
         */
        "windowProvider"?: Window;
        /**
          * Function to call to write to clipboard. This does not need to be set and only exists for injecting in a mock for unit testing.
         */
        "writeToClipboard"?: (_: string) => Promise<void>;
    }
    interface IntrinsicElements {
        "twindle-buildinfo-display": TwindleBuildinfoDisplay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "twindle-buildinfo-display": LocalJSX.TwindleBuildinfoDisplay & JSXBase.HTMLAttributes<HTMLTwindleBuildinfoDisplayElement>;
        }
    }
}
