/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KimnooBuildinfoDisplay {
        /**
          * Function to call to write to clipboard. This does not need to be set and only exists for injecting in a mock for unit testing.
         */
        "writeToClipboard": (_: string) => Promise<void>;
    }
}
declare global {
    interface HTMLKimnooBuildinfoDisplayElement extends Components.KimnooBuildinfoDisplay, HTMLStencilElement {
    }
    var HTMLKimnooBuildinfoDisplayElement: {
        prototype: HTMLKimnooBuildinfoDisplayElement;
        new (): HTMLKimnooBuildinfoDisplayElement;
    };
    interface HTMLElementTagNameMap {
        "kimnoo-buildinfo-display": HTMLKimnooBuildinfoDisplayElement;
    }
}
declare namespace LocalJSX {
    interface KimnooBuildinfoDisplay {
        /**
          * Function to call to write to clipboard. This does not need to be set and only exists for injecting in a mock for unit testing.
         */
        "writeToClipboard"?: (_: string) => Promise<void>;
    }
    interface IntrinsicElements {
        "kimnoo-buildinfo-display": KimnooBuildinfoDisplay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kimnoo-buildinfo-display": LocalJSX.KimnooBuildinfoDisplay & JSXBase.HTMLAttributes<HTMLKimnooBuildinfoDisplayElement>;
        }
    }
}
